### ISSUE TITLE
Practice Guides links broken

### ISSUE THREAD

**Issue by elaineraybourn** [bssw-psip/practice-guides#7]
Hi there,

our links are broken: The 'bssw-psip/practice-guides' repository doesn't contain the 'practice-guides/pages/how_to_start.html' path in 'master'. I get this prompt for all of the pages. Can we please fix this as soon as possible? Someone asked about our PTC catalog today and I wanted to share the instructions with the IDEAS team.

Thanks!

**Comment by mrmundt** [comment]
Hi @elaineraybourn - it contains "https://github.com/bssw-psip/practice-guides/blob/master/pages/how_to_start.md" <- it's a Markdown file that GitHub renders into an HTML file when it gets deployed to the website. Did you find a page where the link is not working?

**Comment by elaineraybourn** [comment]
@mrmundt 

Master renders, all others do not.

https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/why_practice_PSIP.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_start.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_start.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_start.html
https://github.com/bssw-psip/practice-guides/blob/master/ptc-catalog/pages/how-to-contribute.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_execute_plan.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_assess_progress.html

**Comment by mrmundt** [comment]
PR created: #8

**Comment by elaineraybourn** [comment]
@mrmundt thank you so much! I'm always happy to help. :-) I posted the conversation thread below for our reference and future consideration.

From: Mundt, Miranda Rose 
Sent: Thursday, February 23, 2023 2:15 PM
To: Raybourn, Elaine M 
Subject: Re: PSIP practice guides links broken

Yup, no problem! I’ll fix the links. Thanks for playing the thought game with me – I think my understanding of our intended workflow for users is not 100% correct with the actual potential workflows.


From: "Raybourn, Elaine M" 
Date: Thursday, February 23, 2023 at 12:08
To: Miranda Mundt 
Subject: RE: PSIP practice guides links broken

We have at least two types of average users. IDEAS works with teams who have GitHub repos. So, the way these users poke around GitHub is important. 

We would like to have other users (at large)—not accessing through GitHub. 

We need a website, AND a repo that works.

Why can’t we have both? At least for now?


Meanwhile, I can work with DavidB about where to put the PSIP pages – having a website that no one knows is there is not optional either.

Thanks,
Elaine

From: Mundt, Miranda Rose 
Sent: Thursday, February 23, 2023 2:02 PM
To: Raybourn, Elaine M 
Subject: Re: PSIP practice guides links broken

I don’t mean average user of GitHub. I mean average user of PSIP. As in, if we are introducing PSIP to someone for the first time, do we send them to the website or do we send them to the GitHub repository? Where do we want them to go?


From: "Raybourn, Elaine M" 
Date: Thursday, February 23, 2023 at 11:58
To: Miranda Mundt 
Subject: RE: PSIP practice guides links broken

Define average user of GitHub please. 

Also, I’d like to know how many visitors we get to the website.

Thanks,
Elaine

From: Mundt, Miranda Rose 
Sent: Thursday, February 23, 2023 1:48 PM
To: Raybourn, Elaine M 
Subject: Re: PSIP practice guides links broken

I think this a bigger discussion to be had. I don’t assume an average user would be going to the repository. I would assume an average user would be going to the website.

In my view, the intent of the website is to make an easier entry point that abstracts away the “code” and other cruft and just leaves the “information.” It’s the same reason we added a “Download” button to all of the markdown files on the PTC catalog: https://bssw-psip.github.io/ptc-catalog/catalog/AdoptAutomatedCorrectnessTestingInLegacySoftwareProject.html <- So that way they don’t have to sift through the repository for the right markdown file; they can just access it right there after reading it in a nicely-rendered format.

I am fine with changing the links so that it’ll work either way, but it is a good idea to step back here and think about what the purpose of the website is then if we are assuming users are going to the repository first instead of the website.


From: "Raybourn, Elaine M" 
Date: Thursday, February 23, 2023 at 11:44
To: Miranda Mundt 
Subject: RE: PSIP practice guides links broken

Am I accessing the repo the way a user would, who is poking around our repos to see what we have there? I think so. How will a developer know to go to the one webpage that renders all the others correctly? 

Elaine


From: Mundt, Miranda Rose 
Sent: Thursday, February 23, 2023 1:37 PM
To: Raybourn, Elaine M 
Subject: Re: PSIP practice guides links broken

Okay, I think I understand the problem. You are going to https://github.com/bssw-psip/practice-guides and clicking the links on that page, correct?

The way the repository is set up is such that the pages render correctly on the website: https://bssw-psip.github.io/practice-guides/ . The links on the Markdown files are relative links – that is, the links assume you are at the base URL of https://bssw-psip.github.io/ when you are clicking on them.

I can fix this by changing the links to full, permanent links (e.g., https://bssw-psip.github.io/practice-guides/pages/why_practice_PSIP.html), but this isn’t generally a best practice (because it increases the number of changes you have to make if you, for example, refactor the repository or change the base URL).

Up to you what you’d prefer. If you normally work from the repository instead of the website and you prefer that users also do that, I can make the change. If we instead want to push users towards using the website (NOT the repository), then I don’t recommend we change it.

Let me know!



From: "Raybourn, Elaine M" 
Date: Thursday, February 23, 2023 at 11:17
To: Miranda Mundt 
Subject: RE: PSIP practice guides links broken

Master renders, all others do not.

https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/why_practice_PSIP.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_start.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_start.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_start.html
https://github.com/bssw-psip/practice-guides/blob/master/ptc-catalog/pages/how-to-contribute.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_execute_plan.html
https://github.com/bssw-psip/practice-guides/blob/master/practice-guides/pages/how_to_assess_progress.html


From: Mundt, Miranda Rose 
Sent: Thursday, February 23, 2023 12:52 PM
To: Raybourn, Elaine M 
Subject: Re: PSIP practice guides links broken

Hi!

I’m confused – on what page is the link broken? The “how_to_start” page exists in Markdown in the repository: https://github.com/bssw-psip/practice-guides/blob/master/pages/how_to_start.md and renders as an HTML file on the website: https://bssw-psip.github.io/practice-guides/pages/how_to_start.html

Where did you find the broken link?


From: "Raybourn, Elaine M" 
Date: Thursday, February 23, 2023 at 10:48
To: Miranda Mundt 
Subject: PSIP practice guides links broken

I submitted an issue, thanks in advance for your help if you are available!

Elaine
